import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanStackProvider>
          <Header />
          {children}
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import "./globals.css";

// // Імпорт шрифтів (через окремий файл бажано)
// import { Geist, Geist_Mono } from "next/font/google";
// import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
// import Header from "@/components/Header/Header";
// import Footer from "@/components/Footer/Footer";

// // Підключаємо шрифти
// const geistSans = Geist({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-geist-sans",
// });

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-geist-mono",
// });

// export const metadata: Metadata = {
//   title: "Next App Clean Layout",
//   description: "No hydration error example",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <TanStackProvider>
//           <Header />
//           <main>{children}</main>
//           <Footer />
//         </TanStackProvider>
//       </body>
//     </html>
//   );
// }